### ISSUE TITLE
cannot run app locally on clean install

### ISSUE THREAD

**Issue by dgoldstein1** [code-for-charlottesville/housinghub#22]
## Migrations not working

```bash
(venv) david@david-Oryx-Pro:~/dev/personal/housinghub/backend$ $(cd alembic && alembic upgrade head)
Traceback (most recent call last):
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/pgdb.py", line 1653, in connect
    cnx = _connect(dbname, dbhost, dbport, dbopt, dbuser, dbpasswd)
pg.InternalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/dev/personal/housinghub/backend/venv/bin/alembic", line 11, in <module>
    load_entry_point('alembic==1.4.2', 'console_scripts', 'alembic')()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./env.py", line 77, in <module>
    run_migrations_online()
  File "./env.py", line 65, in run_migrations_online
    with connectable.connect() as connection:
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2318, in raw_connection
    self.pool.unique_connection, _connection
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect
    e, dialect, self
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/david/dev/personal/housinghub/backend/venv/lib/python3.6/site-packages/pgdb.py", line 1653, in connect
    cnx = _connect(dbname, dbhost, dbport, dbopt, dbuser, dbpasswd)
sqlalchemy.exc.InternalError: (pg.InternalError) could not translate host name "postgres" to address: Name or service not known

(Background on this error at: http://sqlalche.me/e/2j85)
```

## Tests do not work 

```bash
(venv) david@david-Oryx-Pro:~/dev/personal/housinghub/backend$ coverage run -m pytest
=========================================== test session starts ===========================================
platform linux -- Python 3.6.9, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/david/dev/personal/housinghub/backend
plugins: cov-2.8.1
collected 3 items / 5 errors                                                                              

================================================= ERRORS ==================================================
_______________________________ ERROR collecting src/auth_handlers_test.py ________________________________
ImportError while importing test module '/home/david/dev/personal/housinghub/backend/src/auth_handlers_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/auth_handlers_test.py:2: in <module>
    from server import app, tokenSecret, tokenEncryptAlg
E   ImportError: cannot import name 'tokenSecret'
_____________________________ ERROR collecting src/landlord_handlers_test.py ______________________________
ImportError while importing test module '/home/david/dev/personal/housinghub/backend/src/landlord_handlers_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/landlord_handlers_test.py:4: in <module>
    from auth_handlers import encodeJWT
E   ImportError: cannot import name 'encodeJWT'
_____________________________ ERROR collecting src/navigator_handlers_test.py _____________________________
ImportError while importing test module '/home/david/dev/personal/housinghub/backend/src/navigator_handlers_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/navigator_handlers_test.py:4: in <module>
    from auth_handlers import encodeJWT
E   ImportError: cannot import name 'encodeJWT'
_____________________________ ERROR collecting src/property_handlers_test.py ______________________________
ImportError while importing test module '/home/david/dev/personal/housinghub/backend/src/property_handlers_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/property_handlers_test.py:4: in <module>
    from auth_handlers import encodeJWT
E   ImportError: cannot import name 'encodeJWT'
___________________________________ ERROR collecting src/server_test.py ___________________________________
ImportError while importing test module '/home/david/dev/personal/housinghub/backend/src/server_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/server_test.py:3: in <module>
    from auth_handlers import encodeJWT
E   ImportError: cannot import name 'encodeJWT'
========================================= short test summary info =========================================
ERROR src/auth_handlers_test.py
ERROR src/landlord_handlers_test.py
ERROR src/navigator_handlers_test.py
ERROR src/property_handlers_test.py
ERROR src/server_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================ 5 errors in 1.21s =======================================
```

## App does not start up 

```bash
(venv) david@david-Oryx-Pro:~/dev/personal/housinghub/backend$ serverless wsgi serve
Serverless: Using Python specified in "runtime": python3.6
Unable to import werkzeug (run: pip install werkzeug)
(venv) david@david-Oryx-Pro:~/dev/personal/housinghub/backend$ pip install werkzeug
```

**Comment by thinkharderdev** [comment]
Argh, sorry. I'll sort this out
